spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 5MB
      max-request-size: 10MB
      resolve-lazily: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mvc:
    async:
      request-timeout: 10000  #async请求的超时时间

  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml

  session:
    store-type: none
logging:
#线上放开用
  #config: classpath:bda-log.xml
  level:
    java.sql: debug
    com.apache.ibatis: debug
    com.zj.bda.persistence.mapper: debug
