server:
  port: 18003
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@192.168.234.1:1521:xe
    #username: zjbdatag
    #password: admin
    url: AES@B0A7C29609CCA90887CA50D842B26097003448F5ABEEDA9AC38A0955082B7A8BB31CA670EE8D1D4C24EFE4F2B90FCFF7
    username: AES@9CB03074452B022459CA7B9B899E0D11
    password: AES@2B9CAC16B437F5C3B49F7DF66FB675FB
    platform: oracle
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 1
      max-active: 20
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      filters: wall,stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
      stat-view-servlet:
        login-username: bda
        login-password: bda
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #超时重试次数
      connection-error-retry-attempts: 3
      #必须为false
      break-after-acquire-failure: false

mybatis:
  type-aliases-package: com.zj.bda.persistence.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mapper:
  mappers: com.zj.bda.persistence.grace.BaseMapper
  not-empty: false
  identity: ORACLE
