spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 5MB
      max-request-size: 10MB
      resolve-lazily: false
#  security:
#    user:
#      name: bda
#      password: bda

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    async:
      request-timeout: 10000 #async请求的超时时间


  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
logging:
  #config: classpath:bda-log.xml   线上用
  level:
    java.sql: debug
    com.apache.ibatis: debug
    com.zj.bda.persistence.mapper: debug
security:
  basic:
    enabled: false