--创建单位表
 CREATE TABLE "SYS_UNIT"
   (	"ID" VARCHAR2(16 BYTE) DEFAULT null NOT NULL ENABLE,
	"UNIT_NAME" VARCHAR2(20 BYTE) DEFAULT null NOT NULL ENABLE,
	"PARENT_ID" VARCHAR2(20 BYTE) DEFAULT 0 NOT NULL ENABLE,
	"UNIT_LEVEL" VARCHAR2(200 BYTE) DEFAULT null NOT NULL ENABLE,
	"UNIT_SEQ" VARCHAR2(20 BYTE) DEFAULT 0 NOT NULL ENABLE,
	"UNIT_REMARK" VARCHAR2(400 BYTE) DEFAULT null,
	"OPERATOR_ID" VARCHAR2(16 BYTE) DEFAULT null NOT NULL ENABLE,
	"OPERATE_TIME" DATE DEFAULT null NOT NULL ENABLE,
	"OPERATE_IP" VARCHAR2(20 BYTE) DEFAULT null NOT NULL ENABLE
   ) ;

   COMMENT ON COLUMN "SYS_UNIT"."ID" IS '唯一标识';
   COMMENT ON COLUMN "SYS_UNIT"."UNIT_NAME" IS '单位名称';
   COMMENT ON COLUMN "SYS_UNIT"."PARENT_ID" IS '上级部门id（无上级部门则为"0"）';
   COMMENT ON COLUMN "SYS_UNIT"."UNIT_LEVEL" IS '部门层级（由id逗号拼接的字符串，从上层到底层）';
   COMMENT ON COLUMN "SYS_UNIT"."UNIT_SEQ" IS '部门在当前层级下的顺序，由小到大';
   COMMENT ON COLUMN "SYS_UNIT"."UNIT_REMARK" IS '备注';
   COMMENT ON COLUMN "SYS_UNIT"."OPERATOR_ID" IS '最后一次操作的用户id';
   COMMENT ON COLUMN "SYS_UNIT"."OPERATE_TIME" IS '最后一次操作时间';
   COMMENT ON COLUMN "SYS_UNIT"."OPERATE_IP" IS '最后一次操作ip';

--创建用户表
CREATE TABLE "ZJBDATAG"."SYS_USER"
(	"ID" VARCHAR2(16) NOT NULL ENABLE,
   "USERNAME" VARCHAR2(20) NOT NULL ENABLE,
   "PASSWORD" VARCHAR2(40) NOT NULL ENABLE,
   "UNIT_ID" VARCHAR2(16) NOT NULL ENABLE,
   "STATUS" VARCHAR2(2) NOT NULL ENABLE,
   "REMARK" VARCHAR2(200),
   "OPERATOR_ID" VARCHAR2(16) NOT NULL ENABLE,
   "OPERATE_TIME" DATE NOT NULL ENABLE,
   "OPERATE_IP" VARCHAR2(20) NOT NULL ENABLE
) ;
ALTER TABLE "ZJBDATAG"."SYS_USER" MODIFY ("ID" NOT NULL ENABLE);
COMMENT ON COLUMN "ZJBDATAG"."SYS_USER"."ID" IS '用户唯一标识';
COMMENT ON COLUMN "ZJBDATAG"."SYS_USER"."USERNAME" IS '用户名称（最多20个字节）';
COMMENT ON COLUMN "ZJBDATAG"."SYS_USER"."PASSWORD" IS '用户密码（加密后）';
COMMENT ON COLUMN "ZJBDATAG"."SYS_USER"."UNIT_ID" IS '用户所在单位id';
COMMENT ON COLUMN "ZJBDATAG"."SYS_USER"."STATUS" IS '用户状态（1：正常，0：异常状态，-1：删除状态...后面待定）';
COMMENT ON COLUMN "ZJBDATAG"."SYS_USER"."REMARK" IS '用户备注';
COMMENT ON COLUMN "ZJBDATAG"."SYS_USER"."OPERATOR_ID" IS '最后一次操作用户id';
COMMENT ON COLUMN "ZJBDATAG"."SYS_USER"."OPERATE_TIME" IS '最后一次操作时间';
COMMENT ON COLUMN "ZJBDATAG"."SYS_USER"."OPERATE_IP" IS '最后一次操作ip';